language: node_js

node_js:
  - "8"
  - "9"
  - "10"
  - "11"

services:
  - redis-server

before_install:
  - npm i -g npm@latest
install:
  - npm ci

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run lint
  - npm run test
  - npm run test:e2e

after_script:
  - ./cc-test-reporter format-coverage -t lcov -o coverage/e2e.codeclimate.json coverage/e2e/lcov.info
  - ./cc-test-reporter format-coverage -t lcov -o coverage/unit.codeclimate.json coverage/unit/lcov.info
  - ./cc-test-reporter sum-coverage coverage/*.codeclimate.json -p 2
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi
